# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beio_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['rank', '-is_top', '-published_date', '-created_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
