# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beio_system', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('beio_comments', '0001_initial'),
        ('beio_blog', '0002_auto_20170921_1545'),
        ('beio_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiouser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='BeioUser',
        ),
    ]
